#version 450

#extension GL_EXT_integer_dot_product : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require

#define IQK_MMQ_LUT
#define MMQ
#define B_TYPE block_q8_1_x4
#define B_TYPEV4 block_q8_1_x4_packed128

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

#include "mul_mat_vec_base.glsl"

#include "mmq_iqk.glsl"

#define K_PER_ITER 16

uint a_offset, b_offset, d_offset;

void iter(inout FLOAT_TYPE temp[NUM_COLS][NUM_ROWS], const uint first_row, const uint first_col) {
    i32vec4 qs_a[4];
    i8vec4 a_scales;
    const uint a_ib_row = first_row * p.ncols / QUANT_K + a_offset / 8u;
    const uint a_ib_k = a_ib_row + first_col / QUANT_K;

    const uint16_t laneid = uint16_t(gl_SubgroupInvocationID);
    const uint16_t subid = laneid >> uint16_t(2);
    const uint a_ib_lane = a_ib_k + (laneid & uint16_t(3));
    const float a_blk_scale = float(data_a[a_ib_lane].d);
    prepare_a_k16x_iter(a_ib_lane, qs_a, a_scales);
    const uint b_ib_base = first_col / (QUANT_K_Q8_1 * 4u) + b_offset / 4u;
    const uint b_ib_lane = b_ib_base + 2u * (laneid & uint16_t(3)) + (subid >> uint16_t(1));
    const uint b_blocks_per_col = p.batch_stride_b / (QUANT_K_Q8_1 * 4u);
    const uint b_qs_idx = subid & uint16_t(1);

    [[unroll]] for (uint j = 0; j < NUM_COLS; ++j) {
        i32vec4 qs_b[4];
        float b_scales[4];
        const uint b_block_outer = b_ib_lane + j * b_blocks_per_col;

        [[unroll]] for (uint i = 0; i < 4u; ++i) {
            const f16vec2 b_scale_vec = data_b[b_block_outer].ds[i];
            b_scales[i] = float(b_scale_vec.x);
        }

        [[unroll]] for (uint16_t i = uint16_t(0); i < uint16_t(4); ++i) {
            qs_b[i] = data_b_v4[b_block_outer].qs[b_qs_idx + i * 2u];
        }

        float tmp = 0;
        [[unroll]] for (uint i = 0; i < 4u; ++i) {
            const int32_t q_sum = dotPacked4x8EXT(qs_a[i].x, qs_b[i].x)
                                + dotPacked4x8EXT(qs_a[i].y, qs_b[i].y)
                                + dotPacked4x8EXT(qs_a[i].z, qs_b[i].z)
                                + dotPacked4x8EXT(qs_a[i].w, qs_b[i].w);
            const int32_t scaled_q_sum = a_scales[i] * q_sum;
            tmp += FLOAT_TYPE(b_scales[i] * float(scaled_q_sum));
        }

        temp[j][0] += FLOAT_TYPE(tmp * a_blk_scale);
    }
}

void compute_outputs(const uint32_t first_row) {

    get_offsets(a_offset, b_offset, d_offset);
    a_offset *= QUANT_K / QUANT_K_Q8_1;
    b_offset /= QUANT_K_Q8_1;

    FLOAT_TYPE temp[NUM_COLS][NUM_ROWS];

    [[unroll]] for (uint j = 0; j < NUM_COLS; ++j) {
        temp[j][0] = FLOAT_TYPE(0.0f);
    }

    const uint16_t subgroup_work = uint16_t(K_PER_ITER * 4u * gl_SubgroupSize);
    const uint16_t col_stride = subgroup_work * uint16_t(gl_NumSubgroups);
    uint num_iters = p.ncols / col_stride;

    const uint16_t subgroup_id = uint16_t(gl_SubgroupID);
    uint first_col = subgroup_id * subgroup_work;
    while (num_iters >= 2u) {
        iter(temp, first_row, first_col);
        first_col += col_stride;
        iter(temp, first_row, first_col);
        first_col += col_stride;
        num_iters -= 2u;
    }
    if (num_iters > 0u) {
        iter(temp, first_row, first_col);
        first_col += col_stride;
    }

    const uint16_t laneid = uint16_t(gl_SubgroupInvocationID);
    const uint lane_first_col = first_col + (laneid & uint16_t(3)) * QUANT_K;
    if (lane_first_col < p.ncols) {
        iter(temp, first_row, first_col);
    }

    const uint tid = gl_LocalInvocationID.x;
    reduce_result(temp, d_offset, first_row, 1, tid);
}

void main() {
    const uint first_row = NUM_ROWS * (gl_WorkGroupID.x + gl_NumWorkGroups.x * gl_WorkGroupID.z);

#if defined(DATA_A_IQ2_K) || defined(DATA_A_IQ2_KS)
    init_iq2k_table();
#elif defined(DATA_A_IQ2_KL)
    init_iq2kl_table();
#elif defined(DATA_A_IQ3_K) || defined(DATA_A_IQ3_KS)
    init_iq3k_table();
#elif defined(NEEDS_INIT_IQ_SHMEM)
    init_iq_shmem(gl_WorkGroupSize);
#endif

    if (first_row >= p.stride_d) {
        return;
    }
    compute_outputs(first_row);
}